# Full reference
# https://onbjerg.github.io/foundry-book/reference/config.html

[profile.default]
# Solidity
solc_version = "0.8.13"
optimizer = true
optimizer_runs = 8000

# Gas reporting
gas_reports = ["*"]

verbosity = 1

sender = '0xf1A7dA0000000000000000000000000000000000'
tx_origin = '0xf1A7dA0000000000000000000000000000000000'

[profile.ci]
verbosity = 4
